### ISSUE TITLE
Fix y-overflow in playground

### ISSUE THREAD

**Issue by Forsinge** [modmark-org/modmark#197]
**Describe the bug**
Two scrollbars appear around the output when opening playground on Windows.

*Update: I forgot to include which browser I was running. In the screenshots I am running Chrome (probably version 111).*  

**Screenshots**
![image](https://user-images.githubusercontent.com/89988910/228466593-7bbb45ae-ac06-4b31-813f-fc52d53ec51c.png)

**Comment by CMDJojo** [comment]
There is also a scrolling issue, possibly related to this, which happens on my iPhone when opening the packages view. When I scroll to the bottom of the package list, I don't get to the bottom and the last package is below the screen. If I wait and continue scrolling, I can "scroll away" the taskbar and thus see the last package. I am not that good at CSS to determine if this is the same cause or not. Attaching screen recording below.
