### ISSUE TITLE
Logo ideas

### ISSUE THREAD

**Issue by adelhult** [modmark-org/modmark#229]
It would be great to come up with some ideas for a ModMark logo : )

**Comment by adelhult** [comment]
A few ideas:

![image](https://user-images.githubusercontent.com/11508459/232523174-a31eeace-bf33-42c2-b2a0-6db454cf6aea.png)

**Comment by CMDJojo** [comment]
I think we can take inspiration from the old font-book icon:

![image](https://user-images.githubusercontent.com/25929684/232552583-6502898d-a34e-4414-a267-435cd33ce446.png)

I think it is cool with something looking like you are placing a M character on top of a paper, like building a logo. Here are some (very ugly) mockups of those ideas:

![image](https://user-images.githubusercontent.com/25929684/232552550-ea0a8934-a65d-453a-bc2a-de0b926d5cd8.png)

<img width="364" alt="image" src="https://user-images.githubusercontent.com/25929684/232552521-e82dab19-3cd7-4bfe-815b-59640874318e.png">

(This is sort-of how the third example from Eli looks like above)

**Comment by CMDJojo** [comment]
A way of making it look like the "M" is placed on a paper without actually using shadows (if we don't want 3d-looking elements in an otherwise flat logo):

<img width="200" alt="image" src="https://user-images.githubusercontent.com/25929684/232556791-f1265991-b121-4b01-92ca-4c5b172c8a1d.png">

**Comment by hugomardbrink** [comment]
jag gillar att m skulle vara en gemen, kommunicerar lite att det är lightweight:)

**Comment by adelhult** [comment]
> jag gillar att m skulle vara en gemen, kommunicerar lite att det är lightweight:)

Kanske inte är så dumt! Har du någon idé på färg? Här är lite flera versionen fast med en gemen:
![image](https://user-images.githubusercontent.com/11508459/232703208-6cc56192-6051-477c-8e52-acafd62346f2.png)


(Ska försöka göra något med Jonathans design-idéer sen också!)

**Comment by hugomardbrink** [comment]
Man kan ju kolla lite på färgteori osv haha, vad skulle vi säga demografin skulle bli tillslut, akademiker?

**Comment by adelhult** [comment]
Jo, antar att målgruppen är akademiker och folk som är lite techsavy, passade på att sammanställa vad andra dylika projekt har för loggor också så att man kan anpassa sig lite efter det (och se till att man inte råkar sno någon annans design).

![image](https://user-images.githubusercontent.com/11508459/232712072-ca8cfbc4-75d4-4bbe-8000-e2c2565e7f47.png)

**Comment by hugomardbrink** [comment]
ah snyggt,

Verkar ändå som det är väldigt populärt med blå/grönt eller någon kombination av dem, tycker vi kan hålla oss i den domänen!

**Comment by adelhult** [comment]
Ska sluta prokrastinera och faktiskt börja plugga nu, men här kommer en hög med de varianterna jag har hittils i olika färger (dock med versalt "M" men tänker att det inte spelar så stor roll när man bara kollar på färger):

![Frame 4(2)](https://user-images.githubusercontent.com/11508459/232721305-ae85e545-2277-4e10-b410-0f3e942d73ff.png)

**Comment by adelhult** [comment]
Några fler former:

![image](https://user-images.githubusercontent.com/11508459/232736298-664aaed1-507a-4f6e-a8dd-c0016cd2f0a1.png)

**Comment by adelhult** [comment]
Halloj igen, nu har jag sammanställt de idéer jag kan bidra med (om någon annan har förslag går det jättebra att testa mer med det också) annars tänker jag att vi kanske kan rösta på de former jag tagit fram hittills och sen kan man bestämma färger och finslipa senare:

Rösta genom att reagera med de emojis ni gillar med knappen nere i vänstra hörnet.
![image](https://user-images.githubusercontent.com/11508459/232837185-aade32dc-c09b-491e-9e3d-6ccd44cc8248.png)


![Frame 6](https://user-images.githubusercontent.com/11508459/232836835-7b5874f2-c67f-4533-b1f8-0cb9d1a09dfe.png)
