### ISSUE TITLE
Add variables and schedule when transforms should be executed to respect variable writes and reads

### ISSUE THREAD

**Issue by CMDJojo** [modmark-org/modmark#76]
**Is your feature request related to a problem? Please describe.**
Packages needs access to reading and writing 'environment variables'. This may be done by utilising WASI:s env system, or by providing wrapper functions from the standard library. In any case, we need to be able to expose our host functions. This issue serves to lay the foundation for that, as well as building an environment variable system.

## Subdivision
After slow progress due to discussions on how to actually proceed with this, development has started. We want a scheduler which is closely tied to read/writes to variables so that the language has declarative semantics, but we also want to get variables done. If we rush forward implementing just variables, it may be hard to implement the scheduler afterwards, and it may not be as closely coupled as we would like, but on the other hand, the scheduler is hard to develop without variables. In addition to this, the scheduler is a somewhat complicated system which all by itself takes time to get right.

Development was done by me and @adelhult in a separate repo to make an access-based scheduler, so that all transforms which are writing to a list is scheduled before any reads to it. It seems reasonable to me to split this task into three separate tasks:
- [x] #215
- [x] #216
- [x] #217

**Comment by adelhult** [comment]
This is quite a large task, especially if want a well designed scheduling system that is closely tied to the variable system. So, I think we should break this into smaller parts. I'll start with the first step, which would be building a simple system without any scheduling and with a single global scope. 

It might look something like this: 
* Add a native module `[set key] value` to store assign variables.
* Store global variables in a variable environment inside of the Context struct (we can keep simplify it to a single global scope for now, and think about scoping variables to the closest parent later).
* A primitive way for modules to specify which variables it is interested in reading and writing in their manifest.

**Comment by CMDJojo** [comment]
I have now split up this task to three subtasks, see updated description. I move this to `In progress: Subdivided` and I think we should focus on those tasks one by one, to achieve the original goals of this issue
